import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import TimeLine from "@/components/timeLine";

export default function experiences() {
    return (
        <>
            <Head>
                <title>ALEX'S PORTFOLIO</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
{/*
                <link rel="icon" href="/favicon.ico" />
*/}
            </Head>

            <main  className={styles.main}>
                <TimeLine></TimeLine>
            </main>
        </>
    )
}
