import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import GenericCard from '@/components/GenericCard'
import {Box, Divider, Flex, Wrap} from "@chakra-ui/react";
import Slider from 'react-slick';
import React from "react";

export default function Home() {
    // Settings for the slider

    return (
        <>
            <Head>
                <title>ALEX'S PORTFOLIO</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Box width="100%" maxWidth="1200px" margin="0 auto">
                    <GenericCard
                        description={"ezlk,efkl,egrjkmnergjkmergklmergk,oergjkm erqjkmegrjj"}
                        image={"/next.svg"}>

                    </GenericCard>
                    <GenericCard
                        description={"ezlk,efkl,egrjkmnergjkmergklmergk,oergjkm erqjkmegrjj"}
                        image={"/next.svg"}>

                    </GenericCard>
                </Box>
                <Flex>
                    <Wrap justify={"center"} spacing={30}>


                        <GenericCard
                            description={"ezlk,efkl,egrjkmnergjkmergklmergk,oergjkm erqjkmegrjj"}
                            image={"/next.svg"}>

                        </GenericCard>
                        <GenericCard
                            description={"ezlk,efkl,egrjkmnergjkmergklmergk,oergjkm erqjkmegrjj"}
                            image={"/next.svg"}>

                        </GenericCard>
                        <GenericCard
                            description={"ezlk,efkl,egrjkmnergjkmergklmergk,oergjkm erqjkmegrjj"}
                            image={"/next.svg"}>

                        </GenericCard>
                        <Divider/>

                    </Wrap>
                </Flex>

            </main>
        </>
    )
}
